version: '3'

services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - 11008:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pbdb
      POSTGRES_USER: pbdb_user
      POSTGRES_PASSWORD: pbdb_pass

  postgres_test:
    image: postgres:9.6
    restart: always
    ports:
      - 11010:5432
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pbdbtest
      POSTGRES_USER: pbdb_user
      POSTGRES_PASSWORD: pbdb_pass

