spring:
  datasource:
    url: "jdbc:postgresql://localhost:11002/pbdb"
    username: "d.diallo"
    password: "pass"
    driverClassName: "org.postgresql.Driver"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: public
server:
  port: 8181
logging:
  level:
    org.springframework.web: DEBUG