spring:
  datasource:
    url: "jdbc:postgresql://localhost:11008/pbdb"
    username: "pbdb_user"
    password: "pbdb_pass"
    driverClassName: "org.postgresql.Driver"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8181
logging:
  level:
    org.springframework.web: INFO